TEAM_NAME_MAPPING = {
    "Getafe": "Getafe",
    "Mallorca": "Mallorca",
    "Real Sociedad": "Real Sociedad",
    "Real Oviedo": "Real Oviedo",
    "Rayo Vallecano": "Rayo Vallecano",
    "Celta de Vigo": "Celta de Vigo",
    "Real Madrid": "Real Madrid",
    "AlavÃ©s": "Deportivo Alavés",
    "Espanyol": "Espanyol",
    "Osasuna": "Osasuna",
    "Elche": "Elche",
    "Athletic Club": "Athletic Club",
    "Real Betis": "Real Betis",
    "AtlÃ©tico de Madrid": "Atlético Madrid",
    "Valencia": "Valencia",
    "Girona": "Girona",
    "Levante": "Levante",
    "Sevilla": "Sevilla",
    "Barcelona": "Barcelona",
    "Villarreal": "Villarreal",
    "Fiorentina": "Fiorentina",
    "Genoa": "Genoa",
    "Cremonese": "Cremonese",
    "Juventus": "Juventus",
    "Roma": "Roma",
    "Lazio": "Lazio",
    "Cagliari": "Cagliari",
    "Pisa": "Pisa",
    "Atalanta": "Atalanta",
    "Udinese": "Udinese",
    "Napoli": "Napoli",
    "Sassuolo": "Sassuolo",
    "Hellas Verona": "Hellas Verona",
    "Como": "Como",
    "Lecce": "Lecce",
    "Torino": "Torino",
    "Parma": "Parma",
    "Milan": "Milan",
    "Internazionale": "Internazionale",
    "Bologna": "Bologna",
    "Liverpool": "Liverpool",
    "AFC Bournemouth": "Bournemouth",
    "Sunderland": "Sunderland",
    "Fulham": "Fulham",
    "Arsenal": "Arsenal",
    "Brighton & Hove Albion": "Brighton",
    "West Ham United": "West Ham United",
    "Tottenham Hotspur": "Tottenham Hotspur",
    "Brentford": "Brentford",
    "Burnley": "Burnley",
    "Crystal Palace": "Crystal Palace",
    "Everton": "Everton",
    "Nottingham Forest": "Nottingham Forest",
    "Aston Villa": "Aston Villa",
    "Manchester City": "Manchester City",
    "Newcastle United": "Newcastle United",
    "Manchester United": "Manchester United",
    "Chelsea": "Chelsea",
    "Leeds United": "Leeds United",
    "Wolverhampton Wanderers": "Wolverhampton Wanderers",
    "Nantes": "Nantes",
    "Toulouse": "Toulouse",
    "Lens": "Lens",
    "Le Havre": "Le Havre",
    "Rennes": "Rennes",
    "Angers SCO": "Angers SCO",
    "Metz": "Metz",
    "Lorient": "Lorient",
    "Nice": "Nice",
    "Paris FC": "Paris",
    "Strasbourg": "Strasbourg",
    "Brest": "Brest",
    "Olympique Lyonnais": "Olympique Lyonnais",
    "Lille": "Lille",
    "Paris Saint-Germain": "PSG",
    "Monaco": "Monaco",
    "Auxerre": "Auxerre",
    "Olympique Marseille": "Olympique Marseille",
    "Mainz 05": "Mainz 05",
    "Stuttgart": "Stuttgart",
    "Borussia Dortmund": "Borussia Dortmund",
    "Heidenheim": "Heidenheim",
    "Eintracht Frankfurt": "Eintracht Frankfurt",
    "KÃ¶ln": "Köln",
    "Wolfsburg": "Wolfsburg",
    "Union Berlin": "Union Berlin",
    "Augsburg": "Augsburg",
    "Hamburger SV": "Hamburger SV",
    "Freiburg": "Freiburg",
    "Bayer Leverkusen": "Bayer Leverkusen",
    "Borussia M'gladbach": "Borussia M'gladbach",
    "Werder Bremen": "Werder Bremen",
    "Hoffenheim": "Hoffenheim",
    "St. Pauli": "St. Pauli",
    "RB Leipzig": "RB Leipzig",
    "Bayern MÃ¼nchen": "Bayern München",
}

POSITION_GROUPS = {
    "FW": ["CF", "LW", "LWF", "RW", "RWF"],
    "MF": ["AMF", "DMF", "LAMF", "LCMF", "LDMF", "RAMF", "RCMF", "RDMF"],
    "DF": ["CB", "LB", "LCB", "LWB", "RB", "RCB", "RWB"],
    "GK": ["GK"],
}
